#!/bin/bash

docker run --rm -it --privileged \
    -v $(pwd)/src:/src \
    -v $(pwd)/build:/build \
    -v /dev/ttyACM0:/dev/ttyACM0 \
    inrol-dwm1001-firmware-builder:0.0.1 \
    bash -c "./nrfjprog/bin/nrfjprog --reset -f nrf52"
